# Generated by Django 3.1.7 on 2021-05-23 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kititems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_max', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititems', to='inventory.itemexpiry')),
            ],
        ),
        migrations.CreateModel(
            name='kits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('serial_no', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('kit_type', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=100)),
                ('nearest_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loanorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanee_name', models.CharField(max_length=50)),
                ('loan_end_date', models.DateField()),
                ('loan_active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ordering_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tempcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanded_qty', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititemstemp', to='inventory.itemexpiry')),
                ('item_in_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititemsfortemp', to='inventory.kititems')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kititemstempcart', to='inventory.kits')),
                ('ordering_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kititemscart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('ordertype', models.CharField(default='Withdraw', max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('for_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replenishmentorders', to='inventory.kits')),
                ('ordering_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='loanoutstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityopen', models.IntegerField(default=0)),
                ('quantityunopened', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outstandingloancartitem', to='inventory.itemexpiry')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outstandingloan', to='inventory.loanorder')),
            ],
        ),
        migrations.CreateModel(
            name='loancart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityopen', models.IntegerField(default=0)),
                ('quantityunopened', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('loan', models.BooleanField(default=True)),
                ('expanded', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loancartitem', to='inventory.itemexpiry')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loancart', to='inventory.loanorder')),
            ],
        ),
        migrations.CreateModel(
            name='kitloancart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_end_date', models.DateField(blank=True, null=True)),
                ('loan_active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('other_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('loan', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitloancartitem', to='inventory.kits')),
                ('ordering_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitloanorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kititems',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.kits'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Bandages', 'Bandages'), ('Solution', 'Solution'), ('Dressing', 'Dressing'), ('Universal Precaution', 'Universal Precaution'), ('General', 'General')], default='General', max_length=50)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('min_quantityopen', models.IntegerField(blank=True, default=0, null=True)),
                ('min_quantityunopened', models.IntegerField(blank=True, default=0, null=True)),
                ('expirydates', models.ManyToManyField(null=True, related_name='ParentItem', to='inventory.ItemExpiry')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityopen', models.IntegerField(default=0)),
                ('quantityunopened', models.IntegerField(default=0)),
                ('withdraw', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='inventory.itemexpiry')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='inventory.order')),
            ],
        ),
    ]
