# Generated by Django 3.1.7 on 2021-05-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210523_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemExpiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('quantityopen', models.IntegerField(default=0)),
                ('quantityunopened', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='inventory.itemexpiry'),
        ),
        migrations.AddField(
            model_name='item',
            name='expirydates',
            field=models.ManyToManyField(null=True, related_name='ParentItem', to='inventory.ItemExpiry'),
        ),
        migrations.AddField(
            model_name='kititems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititems', to='inventory.itemexpiry'),
        ),
        migrations.AddField(
            model_name='loancart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loancartitem', to='inventory.itemexpiry'),
        ),
        migrations.AddField(
            model_name='loanoutstanding',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outstandingloancartitem', to='inventory.itemexpiry'),
        ),
        migrations.AddField(
            model_name='tempcart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititemstemp', to='inventory.itemexpiry'),
        ),
    ]
