# Generated by Django 3.1.7 on 2021-05-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210523_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expirydates',
        ),
        migrations.AddField(
            model_name='itemexpiry',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expirydates', to='inventory.item'),
        ),
        migrations.CreateModel(
            name='kititemexpiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirydate', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsexpiry', to='inventory.kits')),
                ('kititem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemexpiry', to='inventory.kititems')),
            ],
        ),
    ]
