# Generated by Django 3.1.7 on 2021-05-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210523_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_quantityopen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='total_quantityunopened',
            field=models.IntegerField(default=0),
        ),
    ]
