# Generated by Django 3.1.7 on 2021-05-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
