# Generated by Django 3.1.7 on 2021-05-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210523_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kititemexpiry',
            name='expirydate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kititemexpiry', to='inventory.itemexpiry'),
        ),
        migrations.AlterField(
            model_name='kititems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititems', to='inventory.item'),
        ),
    ]
