# Generated by Django 3.1.7 on 2021-05-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210527_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcart',
            name='item_in_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kititemsfortemp', to='inventory.kititemexpiry'),
        ),
    ]
