# Generated by Django 3.1.7 on 2021-05-30 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_auto_20210529_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='kit_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('kitloancart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='inventory.kitloancart')),
                ('ordering_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_transaction', to=settings.AUTH_USER_MODEL)),
                ('restock_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_transaction', to='inventory.order')),
            ],
        ),
    ]
