# Generated by Django 3.1.7 on 2021-05-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_kit_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kit_transactions',
        ),
    ]
