# Generated by Django 3.1.7 on 2021-05-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210530_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kit_transactions',
        ),
    ]
