# Generated by Django 3.1.7 on 2021-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_kit_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcart',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
