# Generated by Django 3.1.7 on 2021-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_tempcart_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemexpiry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kititemexpiry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
