# Generated by Django 3.1.7 on 2021-07-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210706_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='itemexpiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemexpiryalerts', to='inventory.itemexpiry'),
        ),
    ]
