# Generated by Django 3.1.7 on 2021-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_tempcart_timeadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcart',
            name='timeadded',
        ),
        migrations.AddField(
            model_name='tempcart',
            name='batchnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
