# Generated by Django 3.1.7 on 2021-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210709_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcart',
            name='batchnum',
            field=models.IntegerField(default=0),
        ),
    ]
