# Generated by Django 3.1.7 on 2021-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20210709_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcart',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
